[package]
name = "food-recall-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
reqwest = "0.11.14"
scraper = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread", "fs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
